config/routes.rb
WorkshopsEngine::Engine.routes.draw do
  resources :workshops
end

app/models/workshops_engine/workshop.rb
module WorkshopsEngine
  class Workshop < ActiveRecord::Base
    # belongs_to :user
    # validates :title, presence: true, uniqueness: true
  end
end

app/controllers/workshops_engine/application_controller.rb
module WorkshopsEngine
  class ApplicationController < ::ApplicationController
    if Rails.env.test?
      layout 'dummy'
    else
      layout 'admin'
    end
  end
end

app/controllers/workshops_engine/workshops_controller.rb
require_dependency "workshops_engine/application_controller"

module WorkshopsEngine
  class WorkshopsController < ApplicationController
    before_action :find_workshop, only: [:show, :edit, :update, :destroy]

    def index
      @workshops = Workshop.all
    end

    def show
    end

    def new
      @workshop = Workshop.new
    end

    def edit
    end

    def create
      @workshop = Workshop.new(workshop_params)
      if @workshop.save
        redirect_to workshops_url, notice: 'Workshop was successfully created.'
   else
        render :new
      end
    end

    def update
      if @workshop.update(workshop_params)
        redirect_to workshops_url, notice: 'Workshop was successfully updated.'
      else
        render :edit
      end
    end

    def destroy
      @workshop.destroy
      redirect_to workshops_url, notice: 'Workshop was successfully destroyed.'
    end
    
    private

    def find_workshop
      @workshop = Workshop.find(params[:id])
    end
    
    def workshop_params
      params.require(:workshop).permit(:title,
                                       :description,
                                       :date_and_time,
                                       :user_id,
                                       :is_published)
    end
  end
end

app/helpers/workshops_engine/application_helper.rb
module WorkshopsEngine
  module ApplicationHelper
    def method_missing method, *args, &block
      puts "LOOKING FOR ROUTES #{method}"
      if method.to_s.end_with?('_path') or method.to_s.end_with?('_url')
        if main_app.respond_to?(method)
          main_app.send(method, *args)
        else
          super
        end
      else
        super
      end
    end

    def respond_to?(method)
      if method.to_s.end_with?('_path') or method.to_s.end_with?('_url')
        if main_app.respond_to?(method)
          true
        else
          super
        end
      else
        super
      end
    end
  end
end

app/helpers/workshops_engine/workshops_helper.rb
module WorkshopsEngine
  module WorkshopsHelper
   
  end
end

app/views/layouts/workshops_engine/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WorkshopsEngine</title>
  <%= stylesheet_link_tag    "workshops_engine/application", media: "all" %>
  <%= javascript_include_tag "workshops_engine/application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/workshops_engine/workshops/_form.html.haml
= simple_form_for(@workshop, html: { multipart: true }) do |f|
  = render partial: 'shared/errors', locals: { resource: @workshop }
  .col-md-3
    .span3
  .col-md-6
    .span12
      .field
        = f.input :title
      .field
        = f.input :description
      .actions
        = link_to 'Cancel', workshops_path, class: 'btn btn-disabled'
        = f.submit 'Save', class: 'btn'
  .col-md-3
    .span3
  
.clearfix

app/views/workshops_engine/workshops/_workshop.html.haml
%tr
  %td= workshop.title
  %td= workshop.description
  %td= link_to 'Show', workshop
  %td= link_to 'Edit', edit_workshop_path(workshop)
  %td= link_to 'Destroy', workshop, method: :delete,
    data: { confirm: 'Are you sure?' }

app/views/workshops_engine/workshops/edit.html.haml
%h1 Editing workshop
= render 'form'
= link_to 'Show', @workshop
|
= link_to 'Back', workshops_path

app/views/workshops_engine/workshops/index.html.haml
%h1 Listing workshops
%table
  %thead
    %tr
      %th Name
      %th Description
      %th{ colspan: 3 }
    %tbody
      = render @workshops
%br
= link_to 'New workshop', new_workshop_path

app/views/workshops_engine/workshops/new.html.haml
%h1 New Workshop
= render 'form'
= link_to 'Back', workshops_path

app/views/workshops_engine/workshops/show.html.haml
%p#notice= notice
%p
  %strong Title:
  = @workshop.title
%p
  %strong Description:
  = @workshop.description
= link_to 'Edit', edit_workshop_path(@workshop)
|
= link_to 'Back', workshops_path